name: Translation

on: push

jobs:
  translation:
    name: Run translation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/translation-action@v1.0.0
        id: translation
        with:
          provider: yandex
          api_key: 'trnsl.1.1.20161125T152027Z.65e73e18a60f3051.7764a7a11754995544ad557501df9e14abbfb6e0'
          lang: 'en-ru'
          source: 'Thank you.'
      - name: Print translation result
        run: echo "${{ steps.translation.outputs.text }}"
